FROM agrigorev/zoomcamp-model:2025

WORKDIR /code

COPY pyproject.toml ./
RUN pip install -e .

COPY question_4.py pipeline_v1.bin ./

EXPOSE 9696
CMD ["uvicorn", "question_4:app", "--host=0.0.0.0", "--port=9696"]